import AppTopBar from "@/components/AppTopBar";
import QueryStateNotice from "@/components/QueryStateNotice";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Check, CheckCircle2, Clipboard, Copy, ExternalLink, Globe2, MoreHorizontal, Plus, RefreshCw, ShieldCheck, Trash2, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const initialDomains = [
  { domain: "altx.io", status: "Verificado", mailboxes: 16, usage: "92 GB", added: "12 mai 2026", dns: "mx.altx.io" },
  { domain: "altxstudio.com", status: "Verificado", mailboxes: 5, usage: "31 GB", added: "04 jun 2026", dns: "mx.altx.io" },
  { domain: "usealtx.com.br", status: "Verificado", mailboxes: 3, usage: "12 GB", added: "17 jun 2026", dns: "mx.altx.io" },
  { domain: "altx-labs.dev", status: "Pendente", mailboxes: 0, usage: "0 GB", added: "Hoje", dns: "mx.altx.io" },
];

export default function Domains() {
  const [domains, setDomains] = useState(initialDomains);
  const domainsQuery = trpc.domains.list.useQuery(undefined, { retry: false });
  const createDomainMutation = trpc.domains.create.useMutation({ onSuccess: () => domainsQuery.refetch() });
  const verifyDomainMutation = trpc.domains.verify.useMutation({ onSuccess: () => domainsQuery.refetch() });
  const removeDomainMutation = trpc.domains.remove.useMutation({ onSuccess: () => domainsQuery.refetch() });
  const [newDomain, setNewDomain] = useState("");
  const [open, setOpen] = useState(false);
  const [selected, setSelected] = useState(initialDomains[0]);
  const liveDomains = domainsQuery.data === undefined ? domains : domainsQuery.data.map((item) => ({ domain: item.domain, status: item.status === "verified" ? "Verificado" : item.status === "suspended" ? "Suspenso" : "Pendente", mailboxes: 0, usage: "0 GB", added: item.createdAt ? new Date(item.createdAt).toLocaleDateString("pt-BR") : "Agora", dns: item.dnsTarget, id: item.id }));
  const displayDomains = liveDomains as typeof domains;
  const addDomain = () => {
    const normalized = newDomain.trim().toLowerCase();
    if (!normalized || !normalized.includes(".")) return toast.error("Informe um domínio válido.");
    createDomainMutation.mutate({ domain: normalized }, { onSuccess: () => toast.success("Domínio persistido. Siga as instruções de DNS para verificar."), onError: () => toast.error("Não foi possível persistir o domínio. Verifique a configuração do servidor.") });
    setNewDomain(""); setOpen(false);
  };
  const verifyDomain = (domain: string) => { const item = liveDomains.find((entry) => entry.domain === domain) as typeof domains[number] & { id?: number } | undefined; if (item?.id) verifyDomainMutation.mutate({ id: item.id }, { onSuccess: () => toast.success(`${domain} marcado como verificado.`), onError: () => toast.error("Não foi possível verificar o domínio na VPS.") }); };
  const removeDomain = (domain: string) => { const item = liveDomains.find((entry) => entry.domain === domain) as typeof domains[number] & { id?: number } | undefined; if (item?.id) removeDomainMutation.mutate({ id: item.id }, { onSuccess: () => toast.success("Domínio removido do workspace."), onError: () => toast.error("Não foi possível remover o domínio da VPS.") }); };
  return (
    <div className="editorial-grid editorial-glow min-h-screen bg-[#071013] text-[#f0f4eb]">
      <AppTopBar eyebrow="Operação / domínios" title={<>Domínios que dão <em className="text-[#c8ff4f]">endereço</em> à sua operação.</>} description="Conecte seus domínios corporativos à infraestrutura de e-mail da VPS, acompanhe o status e mantenha as configurações sob controle." actionLabel="Adicionar domínio" onAction={() => setOpen(true)} />
      <div className="px-5 py-7 sm:px-8 lg:px-12">
        <QueryStateNotice isLoading={domainsQuery.isLoading} isError={domainsQuery.isError} empty={domainsQuery.data !== undefined && domainsQuery.data.length === 0} label="domínios" />
        <div className="mb-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[#2a4d47] bg-[#0d2323] p-5"><div className="micro-label text-[#6f9386]">Total conectado</div><div className="mt-5 text-3xl font-semibold">{displayDomains.length.toString().padStart(2, "0")}</div><p className="mt-1 text-xs text-[#70988a]">domínios no workspace</p></div><div className="rounded-2xl border border-[#2a4d47] bg-[#0d2323] p-5"><div className="micro-label text-[#6f9386]">Status DNS</div><div className="mt-5 flex items-center gap-2 text-3xl font-semibold">{displayDomains.filter((item) => item.status === "Verificado").length}<CheckCircle2 className="h-5 w-5 text-[#c8ff4f]" /></div><p className="mt-1 text-xs text-[#70988a]">domínios verificados</p></div><div className="rounded-2xl border border-[#2a4d47] bg-[#0d2323] p-5"><div className="micro-label text-[#6f9386]">Roteamento</div><div className="mt-5 text-lg font-medium text-[#b7e69c]">mx.altx.io</div><p className="mt-2 text-xs text-[#70988a]">servidor de entrada principal</p></div></div>
        <div className="soft-card overflow-hidden rounded-2xl border hairline"><div className="flex flex-col gap-4 border-b border-[#25443f] px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><div className="micro-label text-[#6d9184]">01 / Inventário</div><h2 className="mt-2 text-xl font-medium">Seus domínios</h2></div><Button variant="outline" onClick={() => toast.success("Sincronização iniciada.")} className="action-button h-9 border-[#3c6955] bg-transparent text-xs text-[#a9d49a] hover:bg-[#183b38] hover:text-[#c8ff4f]"><RefreshCw className="mr-2 h-3.5 w-3.5" />Sincronizar DNS</Button></div><div className="divide-y divide-[#193633]">{displayDomains.map((item) => <div key={item.domain} className="grid gap-4 px-5 py-5 transition-colors hover:bg-[#102b29] sm:grid-cols-[1.5fr_0.8fr_0.7fr_auto] sm:items-center sm:px-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#173630] text-[#a7df90]"><Globe2 className="h-4 w-4" /></div><div><div className="font-medium text-[#e5f0e3]">{item.domain}</div><div className="mt-1 text-xs text-[#6b9181]">Adicionado {item.added}</div></div></div><div><div className="micro-label mb-1 text-[#557c70]">Status</div>{item.status === "Verificado" ? <Badge className="border-0 bg-[#19372f] text-[#b8e99a] hover:bg-[#19372f]"><Check className="mr-1 h-3 w-3" />Verificado</Badge> : <Badge className="border-0 bg-[#3c321b] text-[#edca77] hover:bg-[#3c321b]"><TriangleAlert className="mr-1 h-3 w-3" />Pendente</Badge>}</div><div><div className="micro-label mb-1 text-[#557c70]">Caixas / uso</div><div className="text-sm text-[#bfd0c5]">{item.mailboxes} <span className="text-[#638779]">· {item.usage}</span></div></div><div className="flex items-center justify-end gap-1"><Button variant="ghost" size="icon" onClick={() => { setSelected(item); }} className="h-9 w-9 text-[#72998b] hover:bg-[#183b38] hover:text-[#c8ff4f]" aria-label={`Ver DNS de ${item.domain}`}><ExternalLink className="h-4 w-4" /></Button>{item.status === "Pendente" && <Button variant="ghost" size="icon" onClick={() => verifyDomain(item.domain)} className="h-9 w-9 text-[#72998b] hover:bg-[#183b38] hover:text-[#c8ff4f]" aria-label={`Verificar ${item.domain}`}><ShieldCheck className="h-4 w-4" /></Button>}<Button variant="ghost" size="icon" onClick={() => removeDomain(item.domain)} className="h-9 w-9 text-[#72998b] hover:bg-[#3a2528] hover:text-[#ff9b91]" aria-label={`Remover ${item.domain}`}><Trash2 className="h-4 w-4" /></Button></div></div>)}</div></div>
        <section className="mt-4 grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"><div className="rounded-2xl border border-[#274b47] bg-[#0d2323] p-5 sm:p-6"><div className="micro-label text-[#6d9184]">02 / Como conectar</div><h2 className="mt-3 text-xl font-medium">DNS sem adivinhação.</h2><p className="mt-3 text-sm leading-6 text-[#7fa194]">Depois de adicionar um domínio, publique os registros abaixo no seu provedor. A verificação acontece automaticamente.</p><div className="mt-6 space-y-3"><DnsRow type="MX" host="@" value="mx.altx.io" /><DnsRow type="TXT" host="@" value="v=spf1 include:spf.altx.io ~all" /><DnsRow type="CNAME" host="dkim._domainkey" value="dkim.altx.io" /></div></div><div className="soft-card rounded-2xl border hairline p-5 sm:p-6"><div className="flex items-start justify-between"><div><div className="micro-label text-[#6d9184]">03 / Domínio selecionado</div><h2 className="mt-3 text-xl font-medium">{selected?.domain || "Selecione um domínio"}</h2></div><MoreHorizontal className="h-4 w-4 text-[#6a9184]" /></div><div className="mt-7 rounded-xl border border-dashed border-[#3a6955] bg-[#102b29] p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#c8ff4f]" /><div><div className="text-sm text-[#d5ead5]">Verificação segura</div><p className="mt-1 text-xs leading-5 text-[#80a797]">O AltxCRM valida o DNS antes de liberar novas caixas postais para este domínio.</p></div></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#102523] p-3"><div className="micro-label text-[#557c70]">Entrada</div><div className="mt-2 text-sm text-[#b8d0bf]">mx.altx.io</div></div><div className="rounded-xl bg-[#102523] p-3"><div className="micro-label text-[#557c70]">Saída</div><div className="mt-2 text-sm text-[#b8d0bf]">smtp.altx.io</div></div></div></div></section>
      </div>
      <Dialog open={open} onOpenChange={setOpen}><DialogContent className="border-[#31584e] bg-[#0f2524] text-[#eaf5e8]"><DialogHeader><DialogTitle className="display-font text-3xl">Adicionar domínio</DialogTitle><DialogDescription className="text-[#86a99a]">Comece pelo domínio que você quer conectar ao servidor de e-mail.</DialogDescription></DialogHeader><div className="py-4"><label className="micro-label mb-2 block text-[#739b8b]">Nome do domínio</label><Input value={newDomain} onChange={(event) => setNewDomain(event.target.value)} placeholder="empresa.com.br" className="h-11 border-[#3d6958] bg-[#0a1b1e] text-[#eaf5e8] placeholder:text-[#4f7568]" /></div><DialogFooter><Button variant="ghost" onClick={() => setOpen(false)} className="text-[#87a99a] hover:bg-[#183b38]">Cancelar</Button><Button onClick={addDomain} className="bg-[#c8ff4f] text-[#112119] hover:bg-[#dcff82]">Adicionar domínio</Button></DialogFooter></DialogContent></Dialog>
    </div>
  );
}

function DnsRow({ type, host, value }: { type: string; host: string; value: string }) { const copy = () => { navigator.clipboard?.writeText(value); toast.success("Valor DNS copiado."); }; return <div className="flex items-center gap-3 rounded-xl border border-[#254c43] bg-[#102b29] p-3"><span className="w-12 text-xs font-bold text-[#c8ff4f]">{type}</span><span className="w-28 truncate text-xs text-[#7fa194]">{host}</span><span className="min-w-0 flex-1 truncate text-xs text-[#d0e4d4]">{value}</span><button onClick={copy} className="text-[#6f9b8b] hover:text-[#c8ff4f]" aria-label={`Copiar ${type}`}><Copy className="h-3.5 w-3.5" /></button></div>; }
